# -*- coding: utf-8 -*-
from . import report_close_box
from . import report_close_box_xls
from . import report_close_box_commission
from . import report_close_box_commission2_xls
from . import report_planilla_f07
from . import report_planilla_f07_xls
from . import report_taxpayer
from . import report_taxpayer_xls
from . import report_consumer
from . import report_consumer_xls
from . import report_purchase
from . import report_purchase_xls
from . import report_planilla_f14
from . import report_planilla_f14_xls
from . import report_planilla_f910
from . import report_planilla_f910_xls
from . import report_planilla_f930
from . import report_planilla_f930_xls
from . import report_planilla_f983
from . import report_planilla_f983_xls
from . import report_planilla_f987
from . import report_planilla_f987_xls